spring:
  mail:
    host: smtp.qq.com
    username: xxx@foxmail.com
    password: openyouremail
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    properties.mail.display.sendname: JohnNiang
    default-encoding: utf-8
ncov:
  to:
    - xxx@xxx.com
    - yyy@yyy.com